const INTENT_CATALOG = [
    {
        action: 'request-lookup',
        phrases: [
            'buscar mi envio',
            'buscar envio',
            'buscar otro envio',
            'quiero buscar otro envio',
            'quiero rastrear un envio',
            'quiero rastrear mi envio',
            'quiero consultar un envio',
            'quiero consultar mi envio',
            'quiero buscar un envio',
            'tengo tracking',
            'tengo el tracking',
            'tengo un tracking',
            'tengo el dni',
            'quiero buscar por dni',
            'quiero buscar por tracking',
            'quiero ver otro envio',
            'otro envio',
            'otra busqueda',
            'otro paquete',
        ],
        keywordGroups: [
            ['buscar', 'envio'],
            ['otro', 'envio'],
            ['otra', 'busqueda'],
            ['buscar', 'tracking'],
            ['buscar', 'dni'],
        ],
        keywords: ['buscar', 'rastrear', 'consultar', 'tracking', 'dni', 'otro', 'otra', 'envio'],
    },
    {
        action: 'show-main-menu',
        phrases: [
            'menu',
            'menu principal',
            'ver menu',
            'ver menu principal',
            'inicio',
            'volver al menu',
            'volver al inicio',
            'opciones',
        ],
        keywordGroups: [
            ['menu', 'principal'],
            ['volver', 'menu'],
        ],
        keywords: ['menu', 'inicio', 'opciones'],
    },
    {
        action: 'show-understand-menu',
        phrases: [
            'entender mi envio',
            'quiero entender mi envio',
            'quiero entender que pasa',
            'quiero entender que esta pasando',
            'no entiendo el estado',
            'explicame mi envio',
            'explicame que pasa',
            'ayudame a entender el envio',
        ],
        keywordGroups: [
            ['entender', 'envio'],
            ['explicame', 'envio'],
            ['no', 'entiendo', 'estado'],
        ],
        keywords: ['entender', 'explicame', 'estado', 'envio'],
    },
    {
        action: 'show-location-menu',
        phrases: [
            'donde esta y cuando llega',
            'ubicacion y fecha',
            'seguimiento y fecha',
            'donde esta mi envio y cuando llega',
            'quiero saber donde esta y cuando llega',
        ],
        keywordGroups: [
            ['donde', 'llega'],
            ['ubicacion', 'fecha'],
            ['donde', 'esta', 'cuando', 'llega'],
        ],
        keywords: ['donde', 'ubicacion', 'llega', 'fecha', 'seguimiento'],
    },
    {
        action: 'show-problem-menu',
        phrases: [
            'hubo un problema',
            'tengo un problema con mi envio',
            'problema con el envio',
            'quiero revisar un problema',
            'algo paso con mi envio',
        ],
        keywordGroups: [
            ['problema', 'envio'],
            ['hubo', 'problema'],
            ['algo', 'paso', 'envio'],
        ],
        keywords: ['problema', 'demora', 'reclamo', 'frenado'],
    },
    {
        action: 'show-delivery-menu',
        phrases: [
            'retiro entrega comprobante',
            'retiro o entrega',
            'entrega o comprobante',
            'retiro y entrega',
            'ver entrega o comprobante',
        ],
        keywordGroups: [
            ['retiro', 'comprobante'],
            ['entrega', 'comprobante'],
            ['retiro', 'entrega'],
        ],
        keywords: ['retiro', 'entrega', 'comprobante'],
    },
    {
        action: 'show-management-menu',
        phrases: [
            'cambios y soporte',
            'gestiones y soporte',
            'cambios o soporte',
            'quiero hacer una gestion',
            'quiero ayuda con cambios',
        ],
        keywordGroups: [
            ['cambios', 'soporte'],
            ['gestion', 'soporte'],
        ],
        keywords: ['cambios', 'gestion', 'gestiones', 'soporte'],
    },
    {
        action: 'scroll-faq',
        phrases: [
            'preguntas frecuentes',
            'ver preguntas frecuentes',
            'faq',
            'ayuda frecuente',
        ],
        keywordGroups: [
            ['preguntas', 'frecuentes'],
        ],
        keywords: ['faq', 'preguntas', 'frecuentes'],
    },
    {
        action: 'show-support',
        phrases: [
            'necesito soporte',
            'quiero soporte',
            'hablar con soporte',
            'hablar con una persona',
            'quiero hablar con alguien',
            'pasame con una persona',
            'pasame con un humano',
            'necesito ayuda',
            'quiero hacer un reclamo',
            'quiero un agente',
            'quiero un asesor',
        ],
        keywordGroups: [
            ['hablar', 'persona'],
            ['hablar', 'soporte'],
            ['quiero', 'soporte'],
            ['hacer', 'reclamo'],
        ],
        keywords: ['soporte', 'persona', 'humano', 'agente', 'asesor', 'reclamo', 'ayuda'],
    },
    {
        action: 'show-status',
        phrases: [
            'estado',
            'estado actual',
            'quiero ver el estado',
            'quiero conocer el estado',
            'quiero saber el estado',
            'necesito saber el estado',
            'mostrame el estado',
            'como va',
            'como sigue',
            'en que estado esta',
            'en que esta',
            'decime el estado',
        ],
        keywordGroups: [
            ['estado', 'actual'],
            ['ver', 'estado'],
            ['saber', 'estado'],
            ['como', 'va'],
            ['como', 'sigue'],
        ],
        keywords: ['estado', 'actual', 'saber', 'conocer', 'mostrar'],
    },
    {
        action: 'show-history',
        phrases: [
            'historial',
            'movimientos',
            'movimiento',
            'paso a paso',
            'seguimiento completo',
            'historia',
            'su historia',
            'y su historia',
            'y el historial',
            'la historia del envio',
            'mostrame la historia',
            'mostrame el historial',
        ],
        keywordGroups: [
            ['historial'],
            ['paso', 'paso'],
            ['seguimiento', 'completo'],
            ['su', 'historia'],
        ],
        keywords: ['historial', 'historia', 'movimientos', 'movimiento', 'seguimiento'],
    },
    {
        action: 'show-location',
        phrases: [
            'donde esta',
            'donde anda',
            'por donde anda',
            'por donde va',
            'ubicacion',
            'recorrido',
            'ultima referencia',
            'mostrame donde esta',
            'y donde',
            'donde va',
            'donde esta mi envio',
        ],
        keywordGroups: [
            ['donde', 'esta'],
            ['por', 'donde', 'anda'],
            ['por', 'donde', 'va'],
            ['ultima', 'referencia'],
        ],
        keywords: ['donde', 'ubicacion', 'recorrido', 'referencia', 'mapa', 'gps', 'anda'],
        stageBoosts: {
            en_camino: 2,
            en_sucursal: 2,
            con_problema: 1,
        },
    },
    {
        action: 'show-eta',
        phrases: [
            'cuando llega',
            'fecha estimada',
            'que dia llega',
            'tenia que llegar hoy',
            'cuando me va a llegar',
            'cuando lo entregan',
            'horario de entrega',
            'ventana horaria',
            'eta',
            'estimado',
            'y cuando',
        ],
        keywordGroups: [
            ['cuando', 'llega'],
            ['fecha', 'estimada'],
            ['tenia', 'llegar', 'hoy'],
            ['horario', 'entrega'],
        ],
        keywords: ['cuando', 'llega', 'fecha', 'estimada', 'eta', 'horario'],
        stageBoosts: {
            aun_no_salio: 2,
            en_camino: 2,
            con_problema: 1,
        },
    },
    {
        action: 'show-incidents-menu',
        phrases: [
            'consultar incidencia',
            'consultar incidencias',
            'consultar una incidencia',
            'quiero consultar una incidencia',
            'ver incidencia',
            'ver incidencias',
            'ver mis incidencias',
            'mis incidencias',
            'incidencia',
            'incidencias',
            'tengo una incidencia',
        ],
        keywordGroups: [
            ['consultar', 'incidencia'],
            ['ver', 'incidencia'],
            ['mis', 'incidencias'],
        ],
        keywords: ['incidencia', 'incidencias'],
    },
    {
        action: 'show-issues',
        phrases: [
            'problema',
            'problemas',
            'demora',
            'demorado',
            'retraso',
            'se quedo clavado',
            'no avanza',
            'esta frenado',
            'no se mueve',
            'que paso con mi envio',
            'todavia no me llego',
            'no me llego',
            'hubo un intento fallido',
            'paquete fallido',
        ],
        keywordGroups: [
            ['que', 'paso', 'envio'],
            ['no', 'me', 'llego'],
            ['se', 'quedo', 'clavado'],
            ['no', 'avanza'],
            ['esta', 'frenado'],
            ['intento', 'fallido'],
        ],
        keywords: ['problema', 'demora', 'retraso', 'fallido', 'frenado', 'clavado', 'avanza'],
        stageBoosts: {
            con_problema: 3,
            en_sucursal: 1,
        },
    },
    {
        action: 'show-branch',
        phrases: [
            'sucursal',
            'retiro',
            'retirar',
            'lo puedo pasar a buscar',
            'lo puedo ir a buscar',
            'puedo retirarlo',
            'donde retiro',
            'donde lo busco',
            'paso a buscarlo',
            'quiero retirarlo',
        ],
        keywordGroups: [
            ['lo', 'puedo', 'buscar'],
            ['ir', 'buscar'],
            ['paso', 'buscarlo'],
            ['donde', 'retiro'],
        ],
        keywords: ['sucursal', 'retiro', 'retirar', 'buscarlo', 'buscar'],
        stageBoosts: {
            en_sucursal: 3,
            con_problema: 1,
        },
    },
    {
        action: 'show-pod',
        phrases: [
            'comprobante',
            'comprobante de entrega',
            'constancia de entrega',
            'firma',
            'pod',
            'evidencia',
            'quien recibio',
        ],
        keywordGroups: [
            ['comprobante', 'entrega'],
            ['constancia', 'entrega'],
            ['quien', 'recibio'],
        ],
        keywords: ['comprobante', 'constancia', 'firma', 'pod', 'evidencia', 'recibio'],
        stageBoosts: {
            entregado: 4,
        },
    },
    {
        action: 'show-delivery-issue',
        phrases: [
            'no reconozco la entrega',
            'figura entregado pero no lo tengo',
            'figura entregado pero no llego',
            'dice entregado pero no lo recibi',
            'entregado pero no lo tengo',
            'entregado pero no llego',
            'no recibi el envio',
            'me figura entregado pero no lo tengo',
            'dice entregado y no llego',
            'aparece entregado pero no llego',
            'entregado pero no a mi',
        ],
        keywordGroups: [
            ['entregado', 'no', 'llego'],
            ['entregado', 'no', 'tengo'],
            ['no', 'reconozco', 'entrega'],
            ['no', 'recibi', 'envio'],
        ],
        keywords: ['entregado', 'llego', 'recibi', 'recibido', 'reconozco'],
        stageBoosts: {
            entregado: 5,
        },
    },
    {
        action: 'show-management',
        phrases: [
            'cambiar direccion',
            'modificar entrega',
            'cambiar datos',
            'reprogramar',
            'cancelar',
            'quiero cambiar algo',
            'quiero modificar el envio',
            'quiero reprogramar',
        ],
        keywordGroups: [
            ['cambiar', 'direccion'],
            ['modificar', 'entrega'],
            ['quiero', 'reprogramar'],
            ['quiero', 'cancelar'],
        ],
        keywords: ['cambiar', 'modificar', 'reprogramar', 'cancelar', 'direccion', 'datos'],
        stageBoosts: {
            aun_no_salio: 2,
            en_camino: 1,
        },
    },
    {
        action: 'show-notifications',
        phrases: [
            'notificaciones',
            'notificacion',
            'avisos',
            'mail',
            'email',
            'sms',
            'me notifican',
        ],
        keywordGroups: [
            ['mail', 'sms'],
            ['me', 'notifican'],
        ],
        keywords: ['notificacion', 'notificaciones', 'mail', 'email', 'sms', 'avisos'],
    },
    {
        action: 'report-incident-start',
        phrases: [
            'reportar incidencia',
            'abrir incidencia',
            'crear incidencia',
            'hacer un reclamo',
            'quiero hacer un reclamo',
            'quiero reportar un problema',
            'quiero abrir una incidencia',
            'tengo un reclamo',
            'reclamar',
            'quiero reclamar',
            'iniciar un reclamo',
        ],
        keywordGroups: [
            ['reportar', 'incidencia'],
            ['abrir', 'incidencia'],
            ['hacer', 'reclamo'],
            ['quiero', 'reclamar'],
            ['quiero', 'reportar'],
        ],
        keywords: ['reportar', 'reclamo', 'reclamar', 'abrir', 'crear'],
    },
];

module.exports = {
    INTENT_CATALOG,
};
