name: LogiTrack - CI (Integración Continua)

on:
  push:
    branches: [ "develop", "trunk" ]
  pull_request:
    branches: [ "develop", "trunk" ]

jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Instalar dependencias
      run: npm ci

    - name: Verificar calidad de código (Linter)
      run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: Linter
    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Instalar dependencias
      run: npm ci

    - name: Ejecutar pruebas
      run: npm test
